apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database

spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: mysql

  replicas: 1
  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: password
         - name: MYSQL_DATABASE
           value: test-database

