apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
# This section defines the replicasets for the Pods
spec:
  selector:
    matchLabels:
      app: webapps
      release: "0"

  replicas: 2
  # this is a template for the pods that we are creating. This is similar to creating Pods
  template:
    metadata:
      labels:
        app: webapps
        release: "0"

    spec:
      containers:
      - name: new-deployment
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0
