apiVersion: v1
kind: Pod
metadata:
  name: activemq-release1
  labels:
    app: activemq
    release: "1"

spec:
  containers:
  - name: activemq-release1
    image: richardchesterwood/k8s-fleetman-queue:release1
