apiVersion: v1
kind: Service
metadata:
  name: activemq-release1

spec:
  selector:
    app: activemq
    release: "1"

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort
